/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads */
        get: operations["list_leads_api_v1_leads_get"];
        put?: never;
        /**
         * Create Lead
         * @description Public lead submission (multipart). Returns only an id — nothing else is echoed back.
         */
        post: operations["create_lead_api_v1_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead */
        get: operations["get_lead_api_v1_leads__lead_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Lead
         * @description State transition. 409 (not a silent no-op) if the current state has no edge to the target.
         */
        patch: operations["update_lead_api_v1_leads__lead_id__patch"];
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Resume
         * @description Mint a short-lived presigned URL. The store serves the bytes; the API only authorizes.
         */
        get: operations["get_resume_api_v1_leads__lead_id__resume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_lead_api_v1_leads_post */
        Body_create_lead_api_v1_leads_post: {
            /** Email */
            email: string;
            /** Firstname */
            firstName: string;
            /** Lastname */
            lastName: string;
            /**
             * Resume
             * @description PDF, DOC, or DOCX
             */
            resume: string;
            /**
             * Website
             * @description Honeypot; leave empty
             * @default
             */
            website: string;
        };
        /**
         * EmailKind
         * @enum {string}
         */
        EmailKind: "PROSPECT_CONFIRMATION" | "ATTORNEY_NOTIFICATION";
        /** EmailLogOut */
        EmailLogOut: {
            /** Attempts */
            attempts: number;
            /** Error */
            error: string | null;
            kind: components["schemas"]["EmailKind"];
            /** Recipient */
            recipient: string;
            /** Sentat */
            sentAt: string | null;
            status: components["schemas"]["EmailStatus"];
        };
        /**
         * EmailStatus
         * @enum {string}
         */
        EmailStatus: "PENDING" | "SENT" | "FAILED";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeadCreated */
        LeadCreated: {
            /** Id */
            id: string;
            /**
             * Message
             * @default Thanks! Your information has been received.
             */
            message: string;
        };
        /** LeadDetail */
        LeadDetail: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Email */
            email: string;
            /** Emails */
            emails: components["schemas"]["EmailLogOut"][];
            /** Firstname */
            firstName: string;
            /** Id */
            id: string;
            /** Lastname */
            lastName: string;
            /** Reachedoutat */
            reachedOutAt: string | null;
            reachedOutBy?: components["schemas"]["ReachedOutBy"] | null;
            /** Resumemime */
            resumeMime: string;
            /** Resumename */
            resumeName: string;
            /** Resumesize */
            resumeSize: number;
            state: components["schemas"]["LeadState"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** LeadPage */
        LeadPage: {
            /** Items */
            items: components["schemas"]["LeadSummary"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /**
         * LeadState
         * @enum {string}
         */
        LeadState: "PENDING" | "REACHED_OUT";
        /** LeadSummary */
        LeadSummary: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Email */
            email: string;
            /** Firstname */
            firstName: string;
            /** Id */
            id: string;
            /** Lastname */
            lastName: string;
            /** Reachedoutat */
            reachedOutAt: string | null;
            /** Resumename */
            resumeName: string;
            state: components["schemas"]["LeadState"];
        };
        /** LeadUpdate */
        LeadUpdate: {
            /**
             * State
             * @constant
             */
            state: "REACHED_OUT";
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ReachedOutBy */
        ReachedOutBy: {
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ResumeDownload */
        ResumeDownload: {
            /** Expiresin */
            expiresIn: number;
            /** Filename */
            filename: string;
            /** Url */
            url: string;
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "ATTORNEY" | "ADMIN";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_leads_api_v1_leads_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                state?: components["schemas"]["LeadState"] | null;
                sort?: "newest" | "oldest";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_api_v1_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_lead_api_v1_leads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_api_v1_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lead_api_v1_leads__lead_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_api_v1_leads__lead_id__resume_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeDownload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
